### ISSUE TITLE
azure consumption plan

### ISSUE THREAD

**Issue by krishnasingh1818** [fbeltrao/AzureFunctionExtensions#5]
if am using azure consumption plan then will you product still make new connections to redis server. There are lot of people facing connection issues when using redis cache in functions with consumption plans.

please advise.

**Comment by fbeltrao** [comment]
Hi @krishnasingh1818,
Do you have error logs with the problem? How many calls/sec to Redis are you performing?

**Comment by fbeltrao** [comment]
Closing this. Please reopen if you can provide more information
