### ISSUE TITLE
Error sending event grid events (code: BadRequest)

### ISSUE THREAD

**Issue by Dargos69** [fbeltrao/AzureFunctionExtensions#6]
Hi, I use the EventGrid output extention.
wend I add events to the outputevents, it works really well
but when I send no event, there is an error !
when i see the source code, in AzureFunctionExtensions/src/AzureFunctionExtensions/EventGrid/EventGridOutputAsyncCollector.cs 
FlushAsync should do Nothing if this.eventGridEvents is empty
thanks

**Comment by fbeltrao** [comment]
Hi @Dargos69 thanks for your feedback. Indeed, that is a bug. I am working on a fix.

**Comment by fbeltrao** [comment]
New version fixes this problem.
