### ISSUE TITLE
Microsoft.Azure.WebJobs.Host: Exception binding parameter 'db'. Fbeltrao.AzureFunctionExtensions: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ianpowell2017** [fbeltrao/AzureFunctionExtensions#8]
Hello,

I am struggling and hope you can help.

I have a WebFunction initiated by a QueueTrigger.  When I add your nuget package to my Visual Studio 2017  project and add 
```
[RedisDatabase(Connection = "%redis_connectionstring%")] IDatabase db,
```
and the connection setting in local.settings.json then when I run the webfunction then I get 
```
[30/12/2018 15:52:24] System.Private.CoreLib: Exception while executing function: HttpRequestRedis. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'db'. Fbeltrao.AzureFunctionExtensions: Object reference not set to an instance of an object.
```
My Webfunction looks like this
```
        [FunctionName("HttpRequestRedis")]
        public static async Task Run(
            [QueueTrigger(CloudQueues.TempRequestLoggingForRedis, Connection = "StorageAccount")]string myQueueItem,
            [RedisDatabase(Connection = "%redis_connectionstring%")] IDatabase db,
            ILogger log
           )
          {
          }
```
If I remove the following from the method signature
```
[RedisDatabase(Connection = "%redis_connectionstring%")] IDatabase db,
```
Then it works as expected. Please advise how I may proceed.

Thanks

Ian

**Comment by fbeltrao** [comment]
Hi @ianpowell2017,

Thanks for reporting the problem. I have identified it and applied a fix (currently running).
Please let me know if it works now (I have included an example here: https://github.com/fbeltrao/AzureFunctionExtensions/blob/master/samples/RedisSample/QueueTriggerWithRedisFunctions.cs)

Cheers

**Comment by fbeltrao** [comment]
Version 1.0.22 has the fix
